### ISSUE TITLE
Is there any plan to support other visualization in R package?

### ISSUE THREAD

**Issue by LeeDoYup** [zveryansky/python-arulesviz#3]
Hello. Thx for the awesome project.
I want to ask for you to be going to add other visualizations (matrix-based, grouped matrix, graph-b,  two-key, ..) in R package??

**Comment by zverianskii** [comment]
@LeeDoYup 
tbh I am not sure that they are useful. If you could give some examples how they help to analyse data I will think about additional visualisations.

**Comment by LeeDoYup** [comment]
Thx for the fast reply.
I close this issue, and will reopen if any detailed idea come up with.
